### ISSUE TITLE
Same heating rate output in RADSUM

### ISSUE THREAD

**Issue by vijaykumarsagar** [AER-RC/RADSUM#1]
Hello everyone, Can you help me find out why RADSUM shows the same output (heating rate) even after changing the ozone profile? I have changed the ozone mixing ratio (ppm) in the ozone profile in the RADSUM's TAPE5 file, and I have run this TAPE5 file with LBLRTM to get TAPE31, TAPE32, TAPE33, TAPE61, TAPE62, and TAPE63. After running the RADSUM with the same TAPEs file, I am getting the same output profile.

**Comment by kcadyper** [comment]
Hi, Vijay. Can you provide the TAPE5 you used to run LBLRTM?

**Comment by vijaykumarsagar** [comment]
Hi, Please see the attached file here:
[TAPE5.txt](https://github.com/AER-RC/RADSUM/files/12116477/TAPE5.txt)

**Comment by vijaykumarsagar** [comment]
Hi, [kcadyper](https://github.com/kcadyper), I was unaware of how little the difference actually is. The heating rate is changing very slightly. Therefore, there is no longer a problem with this issue.
